# -*- coding: utf-8 -*-
"""pdf_to_text_Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jubSf2MEW-7jSylLYtVRoAVLSEsz1Urn
"""

!pip install pymupdf pypdf2

import fitz  # PyMuPDF

def extract_text_pymupdf(pdf_path):
    # Open the PDF file
    pdf_document = fitz.open(pdf_path)

    # Initialize a variable to store the extracted text
    extracted_text = ""

    # Loop through each page in the PDF
    for page_num in range(len(pdf_document)):
        page = pdf_document.load_page(page_num)
        text = page.get_text("text")  # Get text from the page
        extracted_text += text

    # Close the PDF file
    pdf_document.close()

    return extracted_text

# Example usage
pdf_path = "/content/election_manual_extracts_state_reorg.pdf"
extracted_text = extract_text_pymupdf(pdf_path)
print(extracted_text)  # You can save this to a file for further processing

with open("/content/output_text.txt", "w", encoding="utf-8") as text_file:
    text_file.write(extracted_text)